
emp1.id=12345
emp1.name=Harriet
emp1.salary=40000
emp1.age=30
emp1.sbu=PES-BU

emp2.id=12346
emp2.name=Shepherd
emp2.salary=50000
emp2.age=26
emp2.sbu=PES-BU

sbuId=PES-BU
sbuName=Product Engineering Services
sbuHead=Kiran Rao